apiVersion: apps/v1
kind: Deployment
metadata:
  name: callme
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: callme
  template:
    metadata:
      labels:
        app.kubernetes.io/name: callme
    spec:
      containers:
        - image: piomin/callme
          name: callme
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: callme
  name: callme
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: callme
  type: ClusterIP